spacing = 2
padding = 0
hide_ascii = false
prefer_small_ascii = false
separator = "~"
key_color = "Blue"
separator_color = "White"

[palette]
type = "Full"
glyph = " "
visible = true

[bar]
glyph = " "
symbol_open = '['
symbol_close = ']'
visible = true
hide_delimiters = false

[box]
title = "─"
visible = true
border = "rounded"

[box.inner_margin]
x = 1
y = 0

[custom_ascii]
#color = "Blue"
path = ".config/macchina/ascii/wow-ascii"

[randomize]
key_color = false
separator_color = false
pool = "plain"

[keys]
host = "host"
kernel = "kern"
battery = "bat"
os = "os"
de = "de"
wm = ""
distro = ""
terminal = ""
shell = "sh"
packages = ""
uptime = "up"
memory = "mem"
machine = "mchn"
local_ip = "ip"
backlight = "brt"
resolution = "res"
cpu_load = "load"
cpu = "cpu"
